import matplotlib.pyplot as plt

class figures:
    def __init__(self, T):
        self.T = range(0, T)

    def tot(self, datas, title):
        plt.figure()
        plt.title('')
        plt.plot(self.T, datas[0], color='black', label='Prem')
        plt.plot(self.T, datas[1], color='r', label='Choi')
        plt.plot(self.T, datas[2], color='deepskyblue', label='Griette/Hilton')
        plt.plot(self.T, datas[3], color='purple', label='Oraby')
        plt.plot(self.T, datas[4], color='orange', label='Rost')
        plt.plot(self.T, datas[5], color='g', label='Yang')
        plt.plot(self.T, datas[6], color='gray', label='New')

        plt.plot(self.T, datas[7], color='black', ls='--')
        plt.plot(self.T, datas[8], color='r', ls='--')
        plt.plot(self.T, datas[9], color='deepskyblue', ls='--')
        plt.plot(self.T, datas[10], color='purple', ls='--')
        plt.plot(self.T, datas[11], color='orange', ls='--')
        plt.plot(self.T, datas[12], color='g', ls='--')
        plt.plot(self.T, datas[13], color='gray', ls='--')

        plt.plot(self.T, datas[14], color='black', ls='--')
        plt.plot(self.T, datas[15], color='r', ls='--')
        plt.plot(self.T, datas[16], color='deepskyblue', ls='--')
        plt.plot(self.T, datas[17], color='purple', ls='--')
        plt.plot(self.T, datas[18], color='orange', ls='--')
        plt.plot(self.T, datas[19], color='g', ls='--')
        plt.plot(self.T, datas[20], color='gray', ls='--')

        plt.grid(False)
        plt.legend()
        plt.title(title)
        plt.xlabel("Time")
        plt.ylabel("Number")

        plt.savefig(title + ".png")
        plt.clf()

    def err(self, datas, title):
        plt.figure()
        plt.title('')
        plt.plot(self.T, datas[0], color='black', label='Prem')
        plt.plot(self.T, datas[1], color='r', label='Choi')
        plt.plot(self.T, datas[2], color='deepskyblue', label='Griette/Hilton')
        plt.plot(self.T, datas[3], color='purple', label='Oraby')
        plt.plot(self.T, datas[4], color='orange', label='Rost')
        plt.plot(self.T, datas[5], color='g', label='Yang')
        plt.plot(self.T, datas[6], color='gray', label='New')

        plt.plot(self.T, datas[7], color='r', ls='--')
        plt.plot(self.T, datas[8], color='deepskyblue', ls='--')
        plt.plot(self.T, datas[9], color='purple', ls='--')
        plt.plot(self.T, datas[10], color='orange', ls='--')
        plt.plot(self.T, datas[11], color='g', ls='--')
        plt.plot(self.T, datas[12], color='gray', ls='--')

        plt.plot(self.T, datas[13], color='r', ls='--')
        plt.plot(self.T, datas[14], color='deepskyblue', ls='--')
        plt.plot(self.T, datas[15], color='purple', ls='--')
        plt.plot(self.T, datas[16], color='orange', ls='--')
        plt.plot(self.T, datas[17], color='g', ls='--')
        plt.plot(self.T, datas[18], color='gray', ls='--')

        plt.grid(False)
        plt.legend()
        plt.title(title)
        plt.xlabel("Time")
        plt.ylabel("Number")
        plt.savefig(title + ".png")
        plt.clf()

    def age(self, datas, title):
        plt.figure()
        plt.title('')
        plt.plot(self.T, datas[0], color='black', ls='--', label='Children')
        plt.plot(self.T, datas[1], color='r', ls='--')
        plt.plot(self.T, datas[2], color='deepskyblue', ls='--')
        plt.plot(self.T, datas[3], color='purple', ls='--')
        plt.plot(self.T, datas[4], color='orange', ls='--')
        plt.plot(self.T, datas[5], color='g', ls='--')
        plt.plot(self.T, datas[6], color='gray', ls='--')

        plt.plot(self.T, datas[7], color='black', ls='-.', label='Adult')
        plt.plot(self.T, datas[8], color='r', ls='-.')
        plt.plot(self.T, datas[9], color='deepskyblue', ls='-.')
        plt.plot(self.T, datas[10], color='purple', ls='-.')
        plt.plot(self.T, datas[11], color='orange', ls='-.')
        plt.plot(self.T, datas[12], color='g', ls='-.')
        plt.plot(self.T, datas[13], color='gray', ls='-.')

        plt.plot(self.T, datas[14], color='black', ls=':', label='Elderly')
        plt.plot(self.T, datas[15], color='r', ls=':')
        plt.plot(self.T, datas[16], color='deepskyblue', ls=':')
        plt.plot(self.T, datas[17], color='purple', ls=':')
        plt.plot(self.T, datas[18], color='orange', ls=':')
        plt.plot(self.T, datas[19], color='g', ls=':')
        plt.plot(self.T, datas[20], color='gray', ls=':')

        plt.grid(False)
        plt.legend()
        plt.title(title)
        plt.xlabel("Time")
        plt.ylabel("Number")
        plt.savefig(title + ".png")
        plt.clf()

